name: Merge_Request

on:
    pull_request:
      types: [opened, synchronize, reopened, closed]



jobs:
    deploy_backend:
      runs-on: ubuntu-latest
      environment: production
  
      steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Publish the app
        run: dotnet publish -c Release --property:PublishDir=publish 
        working-directory: ./backend 
  
  
    deploy_frontend:
      runs-on: ubuntu-latest
      environment: production
  
      steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  
      - name: Build the app
        run: npm install && npm run build && npm run lint
        working-directory: ./frontend    
  